### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kushal34712**
### 🤔 What is the nature of this change? / 这个变动的性质是？

- [ ] New feature / 新特性提交
- [ ] Fix bug / bug 修复
- [ ] Style optimization / 样式优化
- [ ] Code style optimization / 代码风格优化
- [ ] Performance optimization / 性能优化
- [ ] Build optimization / 构建优化
- [ ] Website, documentation, demo improvements / 网站、文档、Demo 改进
- [ ] Refactor code or style / 重构代码或样式
- [ ] Test related / 测试相关
- [ ] Other / 其他

### 🔗 Related Issue / 相关 Issue

(Describe the source of related requirements, such as the related issue discussion link. Example: close #123, close #456. /描述相关需求的来源，如相关的 issue 讨论链接。 例如：close #123, close #456. )

### 💡 Background or solution / 需求背景和解决方案

(The specific problem solved. / 解决的具体问题。)

### 📝 Changelog / 更新日志

(Describe changes from the user side, and list all potential break changes or other risks. / 从用户角度描述具体变化，以及可能的 breaking change 和其他风险。)

### CODE REVIEW

**Review by Umpire2018 — COMMENTED** [review]
The changes in this PR seem to be quite similar to the original content of the README.
I suggest not merging this PR.

**Comment by kushal34712** [comment]
Sir merging this pr will help me so plz merge it

**Comment by Umpire2018** [comment]
@kushal34712 
Could you please explain the specific reasons or benefits for merging this PR? It will help us evaluate the PR more effectively.

**Comment by kushal34712** [comment]
it will be more accruate

**Pull request closed without merging**
